name: test-deploy-site

on: 
  push:
    branches:
      - master

env:
  CI: false
  APP_NAME: DopeGood Store

jobs:
  check-bats-version:
    runs-on: alpine
    if: github.ref == 'refs/heads/master'
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test if build was successful
        run: test -f build/index.html
      - run: grep "$APP_NAME" build/index.html
      - run: npm i -g serve
      - run: serve build &

      - name: Push the build folder to main branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: main # The branch name where you want to push the assets
          FOLDER: build # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message